<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CommandPalette.Extensions" Version="0.11.260520004" />
    <PackageVersion Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
  </ItemGroup>
</Project>
