<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Company>VpnTraffic</Company>
    <Product>VpnTraffic</Product>
    <Version>0.2.0</Version>
    <FileVersion>0.2.0.0</FileVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
  </PropertyGroup>
</Project>
